### ISSUE TITLE
Play and Pause buttons on control bar are visually broken

### ISSUE THREAD

**Issue by Neop0litan** [Tetrax-10/Nord-Spotify#23]
![image](https://user-images.githubusercontent.com/56982408/218329023-dbee5c25-11d0-4a73-b79d-4ca3478b70c4.png)
![image](https://user-images.githubusercontent.com/56982408/218329046-96552407-93d8-4be6-9769-b120d3086596.png)

I did a little bit of tinkering and this gets it closer to looking right but the SVG responsible for making the button darker doesn't fit well.

```css
.main-playPauseButton-button[aria-label="Pause"],
.main-playPauseButton-button[aria-label="Play"] {
    -webkit-mask-size: 32px;
}
```

![image](https://user-images.githubusercontent.com/56982408/218329162-d426fa03-eaf6-40ab-867f-d6d157f71bc3.png)
![image](https://user-images.githubusercontent.com/56982408/218329157-4ce1654f-7ab4-475f-9599-497b453d2034.png)

Scaled up UI to show the SVG issue better.

![image](https://user-images.githubusercontent.com/56982408/218329251-8736aea8-4f66-4722-80be-54b116ed7da3.png)
![image](https://user-images.githubusercontent.com/56982408/218329262-aa26dd25-9a3e-41ee-aaa1-d2c75337201e.png)
